# Generated by Django 4.2.23 on 2025-08-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('unique_files', models.PositiveIntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('actual_size', models.BigIntegerField(default=0)),
                ('storage_savings', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Storage Statistics',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(db_index=True, default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='original_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='files.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='reference_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
