# Generated by Django 4.2.23 on 2025-08-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_storagestats_file_file_hash_file_is_duplicate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicates', to='files.file'),
        ),
    ]
